/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.ControladorAeropuertos;
import modelo.Aeropuerto;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author luciano
 */
public class Lista extends javax.swing.JFrame {

    /**
     * Creates new form Lista
     */
    ControladorAeropuertos conexiones;
    Aeropuerto seleccionado;
    public Lista() throws IOException, FileNotFoundException, ClassNotFoundException {
        initComponents();
        seleccionado=new Aeropuerto();
        conexiones=new ControladorAeropuertos();

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        C1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jFrame1.setMinimumSize(new java.awt.Dimension(546, 670));
        jFrame1.setResizable(false);
        jFrame1.getContentPane().setLayout(null);

        jScrollPane1.setMinimumSize(new java.awt.Dimension(546, 670));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(546, 670));

        jPanel1.setMinimumSize(new java.awt.Dimension(546, 670));
        jPanel1.setLayout(null);

        jLabel2.setText("Lista de Aeropuertos");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(191, 38, 134, 18);

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(10, 530, 72, 24);

        jScrollPane1.setViewportView(jPanel1);

        jFrame1.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 546, 670);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        C1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AerodromoMaria", "AlejandroVelasco", "AlferezFAP", "CapFAPPedroCanga", "CapFAPVictor", "CaptainFAPCarlos", "CaptainFAPGuillermo", "CnlFAPFran", "ComGerman", "CoronoelFAP", "FAPCaptainDavid", "FraciscoCarle", "IncaMancoCapac", "JorgeChavez", "Juanjui", "MariscalLamar", "MoisesBezanquen", "PadreAldamiz", "Pisco", "RodriguezBallon", "SanJuan" }));
        C1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C1MouseClicked(evt);
            }
        });
        C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1ActionPerformed(evt);
            }
        });
        getContentPane().add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(224, 54, -1, -1));

        jLabel1.setText("Selecciona el aeropuerto:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 60, -1, -1));

        B1.setText("Atras");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        getContentPane().add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 176, -1, -1));

        B2.setText("Siguiente");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        getContentPane().add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 176, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon("/home/luciano/NetBeansProjects/Aeropuertos/src/main/java/imagenes/Sin título.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_C1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:
        for(Aeropuerto it:conexiones.getAeropuertos())
            {
                if(it.getCodigo()==C1.getSelectedIndex())
                {
                    seleccionado=new Aeropuerto(it.getNombre()
                            ,it.getCodigo());
                    break;
                }
        }
        jFrame1.setVisible(true);
        for(int i=0;i<conexiones.verConexiones(seleccionado).size();i++)
        {
            javax.swing.JLabel E=new javax.swing.JLabel();
            E.setBounds(0, 50+i*20, 400, 50);
            E.setVisible(true);
            E.setText(conexiones.verConexiones(seleccionado).get(i));
            jPanel1.add(E);
        }
    }//GEN-LAST:event_B2ActionPerformed

    private void C1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_C1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jFrame1.setVisible(false);
        jPanel1.removeAll();
        jPanel1.add(jButton1);
        jPanel1.add(jLabel2);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Menu m=new Menu();
        m.setVisible(true);
    }//GEN-LAST:event_B1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Lista().setVisible(true);
                } catch (IOException | ClassNotFoundException ex) {
                    Logger.getLogger(Lista.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JComboBox<String> C1;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
}
