/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import controladores.ControladorAeropuertos;
import modelo.Aeropuerto;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author luciano
 */
public class Mapa extends javax.swing.JFrame {

    /**
     * Creates new form Mapa
     */
    javax.swing.JCheckBox []boxes;
    int destinos;
    ControladorAeropuertos conexiones;
    Aeropuerto []aeropuertos;
    HashMap<javax.swing.JCheckBox,Aeropuerto> enlace;
    List<Aeropuerto> ruta;
    public Mapa() throws IOException, FileNotFoundException, ClassNotFoundException {
        super("Grafo de Aeropuertos");
        initComponents();
        conexiones=new ControladorAeropuertos();
        aeropuertos=conexiones.getAeropuertos();
        boxes=new javax.swing.JCheckBox[]{AerodromoMaria,AlejandroVelasco,AlferezFAP,
        CapFAPPedroCanga,CapFAPVictor,CaptainFAPCarlos,CaptainFAPGuillermo,CnlFAPFran,
        ComGerman,CoronoelFAP,FAPCaptainDavid,FraciscoCarle,IncaMancoCapac,JorgeChavez,
        Juanjui,MariscalLamar,MoisesBezanquen,PadreAldamiz,Pisco,RodriguezBallon,SanJuan};
        enlace=new HashMap<>();
        ruta=new ArrayList<>();
        for(int i=0;i<boxes.length;i++)
        {
            enlace.put(boxes[i], aeropuertos[i]);
        }
        destinos=0;
        for(javax.swing.JCheckBox it:enlace.keySet())
        {
            it.addActionListener((var ae) -> {
                BoxesActionPerformed(it);
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        JorgeChavez = new javax.swing.JCheckBox();
        ComGerman = new javax.swing.JCheckBox();
        CaptainFAPCarlos = new javax.swing.JCheckBox();
        CaptainFAPGuillermo = new javax.swing.JCheckBox();
        CapFAPVictor = new javax.swing.JCheckBox();
        CapFAPPedroCanga = new javax.swing.JCheckBox();
        MariscalLamar = new javax.swing.JCheckBox();
        Juanjui = new javax.swing.JCheckBox();
        MoisesBezanquen = new javax.swing.JCheckBox();
        CnlFAPFran = new javax.swing.JCheckBox();
        FAPCaptainDavid = new javax.swing.JCheckBox();
        AlferezFAP = new javax.swing.JCheckBox();
        FraciscoCarle = new javax.swing.JCheckBox();
        CoronoelFAP = new javax.swing.JCheckBox();
        Pisco = new javax.swing.JCheckBox();
        AerodromoMaria = new javax.swing.JCheckBox();
        SanJuan = new javax.swing.JCheckBox();
        AlejandroVelasco = new javax.swing.JCheckBox();
        PadreAldamiz = new javax.swing.JCheckBox();
        IncaMancoCapac = new javax.swing.JCheckBox();
        RodriguezBallon = new javax.swing.JCheckBox();
        B1 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jFrame1.setMinimumSize(new java.awt.Dimension(400, 550));
        jFrame1.getContentPane().setLayout(null);

        jPanel2.setLayout(null);

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 460, 72, 24);

        jScrollPane2.setViewportView(jPanel2);

        jFrame1.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 390, 500);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JorgeChavez.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JorgeChavezActionPerformed(evt);
            }
        });
        jPanel1.add(JorgeChavez, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 660, -1, -1));
        jPanel1.add(ComGerman, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, -1, -1));
        jPanel1.add(CaptainFAPCarlos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, -1, -1));

        CaptainFAPGuillermo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaptainFAPGuillermoActionPerformed(evt);
            }
        });
        jPanel1.add(CaptainFAPGuillermo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 20, -1));
        jPanel1.add(CapFAPVictor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, -1, -1));
        jPanel1.add(CapFAPPedroCanga, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));
        jPanel1.add(MariscalLamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));
        jPanel1.add(Juanjui, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, -1, -1));
        jPanel1.add(MoisesBezanquen, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, -1));
        jPanel1.add(CnlFAPFran, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 210, -1, -1));
        jPanel1.add(FAPCaptainDavid, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, -1, -1));
        jPanel1.add(AlferezFAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, -1, -1));
        jPanel1.add(FraciscoCarle, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 650, -1, -1));
        jPanel1.add(CoronoelFAP, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 720, -1, -1));
        jPanel1.add(Pisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 750, -1, -1));
        jPanel1.add(AerodromoMaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 780, -1, -1));
        jPanel1.add(SanJuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 850, -1, -1));
        jPanel1.add(AlejandroVelasco, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 750, -1, -1));
        jPanel1.add(PadreAldamiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 690, -1, -1));
        jPanel1.add(IncaMancoCapac, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 800, -1, -1));
        jPanel1.add(RodriguezBallon, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 900, -1, -1));

        B1.setText("Verificar ruta");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        jPanel1.add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, -1, -1));

        B2.setText("Atras");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        jPanel1.add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 810, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aeropuertos+Perú-960w.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JorgeChavezActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JorgeChavezActionPerformed

    }//GEN-LAST:event_JorgeChavezActionPerformed

    private void CaptainFAPGuillermoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaptainFAPGuillermoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CaptainFAPGuillermoActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
        jFrame1.setVisible(true);
        HashMap<Map<Aeropuerto,Aeropuerto>,Boolean> cierreTransitivo=new HashMap<>(conexiones.metodoWarshall());
        for(int i=0;i<ruta.size()-1;i++)
        {
            
            if(cierreTransitivo.get(Map.of(ruta.get(i),ruta.get(i+1))))
            {
                javax.swing.JLabel E = new javax.swing.JLabel();
                E.setText("Existe ruta entre:"+ruta.get(i).getNombre()+","
                +ruta.get(i+1).getNombre());
                E.setBounds(0,i*20,400,50);
                E.setVisible(true);
                jPanel2.add(E);
            }
            else
            {
                javax.swing.JLabel E = new javax.swing.JLabel();
                E.setText("No existe ruta entre:"+ruta.get(i).getNombre()+","
                +ruta.get(i+1).getNombre());
                E.setBounds(0,i*20,400,50);
                E.setVisible(true);
                jPanel2.add(E);
                break;
            }
        }
    }//GEN-LAST:event_B1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jPanel2.removeAll();
        jFrame1.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Menu m=new Menu();
        m.setVisible(true);
    }//GEN-LAST:event_B2ActionPerformed

    private void BoxesActionPerformed(javax.swing.JCheckBox it)
    {
        if(!it.isSelected())
        {
            destinos=0;
            for(javax.swing.JCheckBox it2:boxes)
            {
                it2.setSelected(false);
                ruta.clear();
                it2.setText("");
            }
        }
        if(destinos==0 && it.isSelected())
        {
            it.setText("Origen");
            ruta.add(enlace.get(it));
            destinos++;
        }
        else if(it.isSelected())
        {
            it.setText("Destino "+destinos);
            ruta.add(enlace.get(it));
            destinos++;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mapa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new Mapa().setVisible(true);
            } catch (IOException | ClassNotFoundException ex) {
                Logger.getLogger(Mapa.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AerodromoMaria;
    private javax.swing.JCheckBox AlejandroVelasco;
    private javax.swing.JCheckBox AlferezFAP;
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JCheckBox CapFAPPedroCanga;
    private javax.swing.JCheckBox CapFAPVictor;
    private javax.swing.JCheckBox CaptainFAPCarlos;
    private javax.swing.JCheckBox CaptainFAPGuillermo;
    private javax.swing.JCheckBox CnlFAPFran;
    private javax.swing.JCheckBox ComGerman;
    private javax.swing.JCheckBox CoronoelFAP;
    private javax.swing.JCheckBox FAPCaptainDavid;
    private javax.swing.JCheckBox FraciscoCarle;
    private javax.swing.JCheckBox IncaMancoCapac;
    private javax.swing.JCheckBox JorgeChavez;
    private javax.swing.JCheckBox Juanjui;
    private javax.swing.JCheckBox MariscalLamar;
    private javax.swing.JCheckBox MoisesBezanquen;
    private javax.swing.JCheckBox PadreAldamiz;
    private javax.swing.JCheckBox Pisco;
    private javax.swing.JCheckBox RodriguezBallon;
    private javax.swing.JCheckBox SanJuan;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
